# Use the official .NET SDK image for the build process
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /app

# Copy the .csproj file and restore dependencies
COPY Server.csproj .
RUN dotnet restore Server.csproj

# Copy the remaining source code
COPY . .

# Build the application in Release mode
RUN dotnet build Server.csproj -c Release -o /app/build

# Define the base image for the final stage of the build process 
FROM build AS publish

# Publish the application
RUN dotnet publish "Server.csproj" -c Release -o /app/publish

# Define the base image for the final stage of the build process
FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80

# Copy the published artifacts from the build stage
COPY --from=publish /app/publish .

# Set the entry point for the container
ENTRYPOINT ["dotnet", "server.dll"]